### PR TITLE
Release preparations

### PR DESCRIPTION
**Pull request by PTaeuberDS**
- Add LICENSE.txt file (copied from fmi-standard, removed "MODELISAR", updated copyright year)
- Add schema files to GitHub Actions artifact
- Change generated revision number in build-ls-xcp.yml

@chrbertsch @t-sommer
Please check! Especially the LICENSE.txt file and the changes regarding the revnumber in build-ls-xcp.yml.

### CODE REVIEW

**Review by andreas-junghanns — APPROVED** [review]

**Comment by chrbertsch** [comment]
The version "v1.0rc1" is not displayed in the generated html: https://github.com/modelica/fmi-ls-xcp/actions/runs/6110148361. @t-sommer : Could you please have a look?
image

**Comment by t-sommer** [comment]
It's displaying the hash because the commit is not tagged.

**Comment by PTaeuberDS** [comment]
@t-sommer 
Ok, so this means, we can merge this PR and afterwards we have to create a tag with a dummy commit directly on the main branch?

**Comment by t-sommer** [comment]
Just tag the commit you want to release and push the tag.

**Pull request merged**
