### PR TITLE
Adapt manifest schema

### PR DESCRIPTION
**Pull request by PTaeuberDS**
This is the schema according to the main standard. To reproduce the different namespaces, two files are needed. The base file fmi-ls-manifest.xsd could also be added to the main standard, because it defines what is written there.

I dropped the prefix in the variable names, because the variables are already prefixed by the namespace.
E.g. fmi-ls:fmi-ls-name -> fmi-ls:name

If that is fine it must be changed in the main standard as well. Otherwise it must be changed here again.

@pmai @andreas-junghanns @chrbertsch
Please have a look

### CODE REVIEW

**Review by chrbertsch — APPROVED** [review]
From my side this looks good, but @pmai  and @andreas-junghanns  should comment on the namespace- and xsd related stuff.

**Comment by chrbertsch** [comment]
FMI Design Webmeeting: 
Andreas: it sounds good to move the common xsd to the fmi standard. 
Christian: Let's get @pmai 's feedback, and then adapt the PR

**Review by andreas-junghanns — APPROVED** [review]

**Review by andreas-junghanns — APPROVED** [review]
There are some violations of one-sentence-per-line, but in tables and with short sentences, I think this is ok.

**Comment by andreas-junghanns** [comment]
@pmai : For the xsd stuff, I think you need to look into this PR. Also to make sure we move the respective base xsd into fmi-standard for the 3.0.1 release...

**Comment by PTaeuberDS** [comment]
I updated the document and manifest schema according to the manifest definition in the base standard that we agreed on.

**Review by andreas-junghanns — APPROVED** [review]

**Review by pmai — APPROVED** [review]
Looks good from my side.

Might in the future either place the FMI 3.0.1 schema files some place accessible and reference from there or work via submodules. But that is for the fmi-standard first to decide.

**Review by chrbertsch — APPROVED** [review]

**Pull request merged**
